


services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Breiner0711
      MYSQL_DATABASE: restaurante_ing
    ports:
      - "3307:3306"
    networks:
      - restaurante-network

  backend:
    build:
      context: C:\Proyecto Restaurante\backend-spring-boot
      dockerfile: Dockerfile  
    image: infraestructura-backend:latest
    ports:
      - "5454:5454"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/restaurante_ing
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Breiner0711
    networks:
      - restaurante-network

  frontend:
    build:
      context: C:\Proyecto Restaurante\frontend-react
      dockerfile: Dockerfile  
    image: infraestructura-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - restaurante-network

networks:
  restaurante-network:
    driver: bridge
